# Generated by Django 5.2.4 on 2025-07-19 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_addictionoption_goaloption_milestoneoption_addiction_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupportContact',
        ),
    ]
