# Generated by Django 5.2.4 on 2025-07-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_privacypolicy_supportcontact_termsconditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingdata',
            name='triggers_text',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
