# Generated by Django 5.2.4 on 2025-07-22 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_onboardingdata_triggers_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingdata',
            name='user',
        ),
    ]
