# Generated by Django 5.2.4 on 2025-07-23 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_onboardingdata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingdata',
            name='improvement_goals',
        ),
        migrations.RemoveField(
            model_name='onboardingdata',
            name='selected_milestone',
        ),
        migrations.RemoveField(
            model_name='usagetracking',
            name='user',
        ),
        migrations.RenameField(
            model_name='onboardingdata',
            old_name='addictions',
            new_name='addiction_option',
        ),
        migrations.RenameField(
            model_name='onboardingdata',
            old_name='triggers_text',
            new_name='trigger_text',
        ),
        migrations.RemoveField(
            model_name='addiction',
            name='answer_1',
        ),
        migrations.RemoveField(
            model_name='addiction',
            name='answer_2',
        ),
        migrations.RemoveField(
            model_name='addiction',
            name='answer_3',
        ),
        migrations.RemoveField(
            model_name='addiction',
            name='user',
        ),
        migrations.AddField(
            model_name='addictionoption',
            name='addiction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.addiction'),
        ),
        migrations.AddField(
            model_name='onboardingdata',
            name='addiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.addiction'),
        ),
        migrations.CreateModel(
            name='DayPerWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(default=0)),
                ('addiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.addiction')),
            ],
        ),
        migrations.CreateModel(
            name='TimesPerDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.IntegerField(default=0)),
                ('addiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.addiction')),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('addiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.addiction')),
            ],
        ),
        migrations.DeleteModel(
            name='GoalOption',
        ),
        migrations.DeleteModel(
            name='MilestoneOption',
        ),
        migrations.DeleteModel(
            name='UsageTracking',
        ),
    ]
