# Generated by Django 5.2.4 on 2025-07-24 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_improvequestion_improvequestionoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingdata',
            name='improvement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.improvequestion'),
        ),
        migrations.AddField(
            model_name='onboardingdata',
            name='improvement_option',
            field=models.ManyToManyField(blank=True, null=True, to='main.improvequestionoption'),
        ),
    ]
