# Generated by Django 5.2.4 on 2025-07-24 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_milestonequestion_milestoneoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingdata',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.milestonequestion'),
        ),
        migrations.AddField(
            model_name='onboardingdata',
            name='milestone_option',
            field=models.ManyToManyField(blank=True, null=True, to='main.milestoneoption'),
        ),
    ]
