# Generated by Django 5.2.4 on 2025-07-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_savinggoal_savinghistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savinghistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='SavingGoal',
        ),
        migrations.DeleteModel(
            name='SavingHistory',
        ),
    ]
