# Generated by Django 5.2.4 on 2025-07-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_moneysaved_recoverymilestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneysaved',
            name='saved_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
