# Generated by Django 5.2.4 on 2025-07-29 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_moneysaved_saved_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneysaved',
            name='goal_amount',
        ),
        migrations.RemoveField(
            model_name='moneysaved',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='moneysaved',
            name='target_days',
        ),
        migrations.CreateModel(
            name='TargetGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_month', models.DateField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
