# Generated by Django 5.2.4 on 2025-07-30 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
