# Generated by Django 5.2.4 on 2025-07-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
