# Generated by Django 5.2.4 on 2025-08-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_journalentry_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='color',
            field=models.CharField(default='blue', max_length=20),
        ),
    ]
