# Generated by Django 5.2.4 on 2025-08-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_journalentry_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingdata',
            name='created_at',
            field=models.TextField(blank=True, null=True),
        ),
    ]
