# Generated by Django 5.2.4 on 2025-08-23 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_onboardingdata_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='targetgoal',
            constraint=models.UniqueConstraint(fields=('user', 'target_month'), name='unique_user_target_month'),
        ),
    ]
